import type { Metadata } from "next";
import { AtlasClient, type AtlasClientPreview } from "@/app/atlas/atlas-client";

export const metadata: Metadata = {
  title: "Atlas Live Layout Preview",
  robots: { index: false, follow: false },
};

const atlasPreview: AtlasClientPreview = {
  selectedCode: "31010101",
  nodes: [
    {
      code: "31010101",
      parent_code: "31010100",
      subject: "evidence",
      subject_display: "Evidence",
      subtopic: "Presentation of Evidence",
      outline_text: "Roles of judge and jury",
      display_label: "Roles of judge and jury",
      level: 2,
      leaf: true,
      question_count: 5,
      leadme_item_count: 7,
      debrief_element_count: 4,
      leadme_set_count: 1,
    },
    {
      code: "31010102",
      parent_code: "31010100",
      subject: "evidence",
      subject_display: "Evidence",
      subtopic: "Presentation of Evidence",
      outline_text: "Burden of production and burden of persuasion",
      display_label: "Burden of production and burden of persuasion",
      level: 2,
      leaf: true,
      question_count: 4,
      leadme_item_count: 4,
      debrief_element_count: 2,
      leadme_set_count: 1,
    },
    {
      code: "31010103",
      parent_code: "31010100",
      subject: "evidence",
      subject_display: "Evidence",
      subtopic: "Presentation of Evidence",
      outline_text: "Presumptions and inferences",
      display_label: "Presumptions and inferences",
      level: 2,
      leaf: true,
      question_count: 3,
      leadme_item_count: 3,
      debrief_element_count: 1,
      leadme_set_count: 1,
    },
    {
      code: "31010104",
      parent_code: "31010100",
      subject: "evidence",
      subject_display: "Evidence",
      subtopic: "Presentation of Evidence",
      outline_text: "Materiality and probative value",
      display_label: "Materiality and probative value",
      level: 2,
      leaf: true,
      question_count: 2,
      leadme_item_count: 2,
      debrief_element_count: 3,
      leadme_set_count: 1,
    },
    {
      code: "31010105",
      parent_code: "31010100",
      subject: "evidence",
      subject_display: "Evidence",
      subtopic: "Presentation of Evidence",
      outline_text: "Offers of proof",
      display_label: "Offers of proof",
      level: 2,
      leaf: true,
      question_count: 1,
      leadme_item_count: 2,
      debrief_element_count: 1,
      leadme_set_count: 1,
    },
    {
      code: "31020101",
      parent_code: "31020100",
      subject: "evidence",
      subject_display: "Evidence",
      subtopic: "Witnesses",
      outline_text: "Mode and order of witnesses",
      display_label: "Mode and order of witnesses",
      level: 2,
      leaf: true,
      question_count: 0,
      leadme_item_count: 1,
      debrief_element_count: 0,
      leadme_set_count: 1,
    },
    {
      code: "21010101",
      parent_code: "21010100",
      subject: "contracts",
      subject_display: "Contracts",
      subtopic: "Formation",
      outline_text: "Offer, acceptance, and consideration",
      display_label: "Offer, acceptance, and consideration",
      level: 2,
      leaf: true,
      question_count: 6,
      leadme_item_count: 4,
      debrief_element_count: 2,
      leadme_set_count: 1,
    },
    {
      code: "22010101",
      parent_code: "22010100",
      subject: "torts",
      subject_display: "Torts",
      subtopic: "Negligence",
      outline_text: "Duty and breach",
      display_label: "Duty and breach",
      level: 2,
      leaf: true,
      question_count: 7,
      leadme_item_count: 5,
      debrief_element_count: 2,
      leadme_set_count: 1,
    },
    {
      code: "11010101",
      parent_code: "11010100",
      subject: "civil_procedure",
      subject_display: "Civil Procedure",
      subtopic: "Jurisdiction",
      outline_text: "Personal jurisdiction",
      display_label: "Personal jurisdiction",
      level: 2,
      leaf: true,
      question_count: 5,
      leadme_item_count: 3,
      debrief_element_count: 2,
      leadme_set_count: 1,
    },
    {
      code: "12010101",
      parent_code: "12010100",
      subject: "constitutional_law",
      subject_display: "Constitutional Law",
      subtopic: "Judicial Review",
      outline_text: "Standing and ripeness",
      display_label: "Standing and ripeness",
      level: 2,
      leaf: true,
      question_count: 4,
      leadme_item_count: 2,
      debrief_element_count: 1,
      leadme_set_count: 1,
    },
    {
      code: "23010101",
      parent_code: "23010100",
      subject: "criminal_law",
      subject_display: "Criminal Law",
      subtopic: "Homicide",
      outline_text: "Murder and manslaughter",
      display_label: "Murder and manslaughter",
      level: 2,
      leaf: true,
      question_count: 4,
      leadme_item_count: 2,
      debrief_element_count: 1,
      leadme_set_count: 1,
    },
    {
      code: "24010101",
      parent_code: "24010100",
      subject: "real_property",
      subject_display: "Real Property",
      subtopic: "Ownership",
      outline_text: "Present and future interests",
      display_label: "Present and future interests",
      level: 2,
      leaf: true,
      question_count: 4,
      leadme_item_count: 2,
      debrief_element_count: 1,
      leadme_set_count: 1,
    },
  ],
  questionsByCode: {
    "31010101": [
      {
        question_id: "ATLAS-PREVIEW-001",
        outline_code: "31010101",
        stem: "A party offers disputed foundation testimony before the jury hears the exhibit.",
        call_text: "Who decides the preliminary admissibility question?",
      },
      {
        question_id: "ATLAS-PREVIEW-002",
        outline_code: "31010101",
        stem: "The judge must decide whether privilege applies before the evidence reaches the jury.",
        call_text: "Which decisionmaker controls the admissibility ruling?",
      },
      {
        question_id: "ATLAS-PREVIEW-003",
        outline_code: "31010101",
        stem: "A conditional relevance issue depends on whether another witness later supplies a link.",
        call_text: "What threshold must the proponent satisfy?",
      },
    ],
  },
  componentsByCode: {
    "31010101": {
      outline_code: "31010101",
      leadme_set: {
        set_id: "atlas-preview-leadme-31010101",
        title: "Roles of judge and jury repair path",
        set_type: "atlas_lesson",
        total_items: 7,
      },
      leadme_items: [
        { component_type: "lesson_micro_read", count: 1 },
        { component_type: "drill_sequence", count: 2 },
        { component_type: "flashcard_checkpoint", count: 3 },
        { component_type: "boot_camp_checkpoint", count: 1 },
      ],
      debrief_elements: [
        { component_type: "trap_decisionmaker_inversion", count: 2 },
        { component_type: "tension_judge_vs_jury", count: 1 },
        { component_type: "answer_debrief", count: 1 },
      ],
      leadme_item_previews: [
        {
          item_id: "atlas-preview-item-1",
          external_id: "PREVIEW-LESSON-104A",
          component_type: "lesson_micro_read",
          estimated_seconds: 360,
        },
        {
          item_id: "atlas-preview-item-2",
          external_id: "PREVIEW-DRILL-104B",
          component_type: "drill_sequence",
          estimated_seconds: 420,
        },
        {
          item_id: "atlas-preview-item-3",
          external_id: "PREVIEW-FLASH-104",
          component_type: "flashcard_checkpoint",
          estimated_seconds: 180,
        },
      ],
      debrief_element_previews: [
        {
          element_id: "atlas-preview-debrief-1",
          component_type: "trap_decisionmaker_inversion",
          title: "Decisionmaker inversion",
          source_count: 3,
        },
        {
          element_id: "atlas-preview-debrief-2",
          component_type: "tension_judge_vs_jury",
          title: "Judge screens, jury weighs",
          source_count: 2,
        },
      ],
      detour_previews: [
        {
          type: "trap",
          key: "decisionmaker-inversion",
          label: "Decisionmaker inversion",
          target_count: 3,
          visibility: "student",
        },
        {
          type: "tension",
          key: "judge-vs-jury",
          label: "Judge versus jury",
          target_count: 2,
          visibility: "student",
        },
      ],
    },
  },
};

export default function AtlasLivePreviewPage() {
  return <AtlasClient preview={atlasPreview} />;
}
